server.js

updated server js with sql stuff, cleaned up section  a little. tested locally, npm start still opened everything and ran.

serverjs file

---

client/src/pages/Home.js

Not clear exactly what this was, but I made component directory capitalized and just re typed where I imported it and seems to work fine again for me.

fixed issue src not found 

---

controllers/commentController.js
controllers/ticketController.js

Comment controller crud

---

controllers/userController.js

Completed basic User CRUD logic:

User controller crud

---

client/src/App.js
client/src/pages/Home.js
client/src/pages/Test.js
client/src/utils/API.js
controllers/authController.js
routes/api/auth.js

- Added routing logic to App.js
- Added function and api call to see if user is logged in or not
- Routing ternary logic currently commented out so we can see the pages as we develop.
If you want to test the routing ternary, simply uncomment them in App.js
- For more realistic testing, we need login page logic to sent a api requst

Auth middleware

---

client/src/App.js
client/src/components/LoginCard/index.js
client/src/pages/Login.js
client/src/utils/API.js

- Updated client/src/App.js to route to login page when exact path is /login.
- updated client/src/utils/API.js to do a POST API call to /api/auth/login (passing the email and password).
- added client/src/components/LoginCard/index.js to contain/build login page content.
- added client/src/pages/Login.js to render login page content and handle the form submit logic.
** right now the styling of the login page needs work, but wanted to get it pushed etc.

created login page and logic for it

---

client/src/components/Navbar/index.js
client/src/pages/Login/index.js

- Added buttons to navbar for login and logout (will add code later to only display one at a time)
- Changed default route so once logged in you are taken to the dashboard page and not the profile page

Login logout buttons

---

client/src/App.js
client/src/components/Navbar/index.js
client/src/components/Wrapper/index.js
client/src/pages/Logout/index.js
client/src/utils/API.js
controllers/authController.js

Added code to track the logged in state of the user.
Added temp header to each page to show if user is logged in.
*Next need to work on adding logic to check logged in state and drive decisions based off of it

Logged in state changes

---

client/package-lock.json
client/src/components/Navbar/index.js
package-lock.json

- Changed Navbar component to use NavLink tags instead of Link tags.
- NavLink tags have auto logic to make link active.
- Removed old logic using path name etc.

fix active nav link issue

---

client/src/App.js
client/src/components/Navbar/index.js
client/src/components/Wrapper/index.js

- Added logic in Navbar component to check the logged in state. Depending on users state, display only one of the buttons.
- Changed state code back to using hooks.
- Updated route list to stop pages from rendering twice.

Login/Logout Buttons - Show/Hide based on Logged In State

---

client/src/components/ManageTicketModal/index.js
client/src/utils/API.js

delete functionality updated

---

client/src/components/EmployeeCard/index.js
client/src/components/EmployeeCardContainer/index.js

sorts left to right, video attached. as noted when we do our styling we can change conditions and look based on conditions. for now its just top two available show green text. updates to employee card container and employee card components. 
https://user-images.githubusercontent.com/72420733/118411819-8dfbb400-b664-11eb-876a-186fa05cdfd6.mp4

Employee card sort

---

client/src/components/EmployeeCardContainer/index.js
client/src/pages/Dashboard/index.js

- Refactored how Dashboard.js States are initialized; 
- Refactored how props are used to send the state data from dashboard to the sub-components
Summary of changes:
- Adjusted the Dashboard.js states for users, clients & tickets to include the proper nested object/arrays
- Changed the props to send the states we adjusted, removing the ternary logic in the props.
- Filter employee logic
In summary:
- The ternaries in the props was causing issues with data compiling.
- Need to set the states up properly first then just send the state down and all the components are happy.

Refactor Dashboard.js States and Props; Filter Employee Logic

---

client/src/components/CommentDiv/index.js
client/src/components/CommentsContainer/index.js
client/src/components/ManageTicketModal/index.js
client/src/utils/API.js

tested stuff and all working for me. notes below. Some warnings in console since refactor, took a quick stab but couldnt find exactly where keys were missing. has not impacted functionality though we can prob do a cleanup in a later branch when we style.

Create comments mvp

---

client/package-lock.json
client/src/components/EmployeeCard/index.js
client/src/components/EmployeeCardContainer/index.js
client/src/components/Navbar/index.js
client/src/components/StatCard/index.js
client/src/components/StatCardContainer/index.js
client/src/pages/Dashboard/index.js
package-lock.json

- Made changes to contents across the top of the dashboard (lined up buttons and made them clickable).
- Made the employee cards on the dashboard clickable.
- Added filter logic in pages/dashboard/index.js file to accept params that will drive the ticket data.
- Made changes to the Navbar logic so only the Home and Login buttons appear when not logged in.
- Added logic in pages/dashboard/index.js to filter ticket data based on passed data from click event.
- Added onclick logic to the employee card comps.
- Added onclick logic to the stats card comps.

Make dashboard buttons clickable / add filter logic on ticket data and make navbar changes

---

client/src/components/StatCardContainer/index.js
client/src/pages/Dashboard/index.js

Updated logic so that we store the counters straight after we do the fetch all on the ticket data (before we filter the data).
Passed fields down the chain and changed the logic to use the passed fields.

Added logic to make counters of ticket stats and store in state fields

---

client/src/components/EmployeeCard/index.js
client/src/components/StatCard/index.js
client/src/pages/Dashboard/index.js

Made changes so that when you are using one of the filters a border appears around the selected filter - so you know which filter is active.

Highlight filter choice

---

client/src/components/CreateTicketModal/index.js
client/src/components/ManageTicketModal/index.js
client/src/components/TicketTable/index.js
client/src/pages/Dashboard/index.js

Client page mvp

---

client/src/components/EmployeeCard/index.js
client/src/components/EmployeeCardContainer/index.js
client/src/components/ProfileForm/index.js
client/src/pages/Dashboard/index.js

badge color conditoinal logic
Notes copied below

Employee card style updates

---

controllers/teamController.js

Fixed bug by fixing the controller req.session.id to user_id

Fixed bug by changing controller logic to use user_id session

---

client/src/components/NewClientForm/index.js

- Fixed Org Page > New Client > Firm Name Label to **Firm**

Fixed typo in org page / new client

---

client/package-lock.json
client/src/components/Navbar/index.js
client/src/components/StatCard/index.js
client/src/components/StatCardContainer/index.js
client/src/pages/Dashboard/index.js
package-lock.json

- Removed "Assigned To Me" filter button from Client Dashboard view
- Refactored code that resets the border on the statcards
- Commented out Team Page logic from Navbar

Update ticket statcard display

---

client/src/components/NewClientForm/index.js
client/src/components/SignupCard/index.js
client/src/pages/Profile/index.js
client/src/pages/Signup/index.js

Grid system update on profile page to make framework for brandons rewards stuff. Will stack at mobile breakpoint but not opitizied for mobile yet

Styling updates ctd

---

client/src/components/ProfileForm/index.js
client/src/components/Progress-Bar/index.js
client/src/components/RewardsContainer/index.js
client/src/pages/Profile/index.js
client/src/utils/API.js
controllers/rewardController.js
routes/api/reward.js
seeds/reward-seeds.js
seeds/ticket-org-1-team-1.js

- Completed Reward Container
- Added Dynamic rendering of reward icons which tracks progress based on your points
- Added Logic to fill in the color of reward icons if you have achieved them
- Completed progress bar logic to show percent left until next reward
- Adjusted seeds slightly

Reward system part 2

---

client/public/index.html

Modiefied index.html for direct rel paths

---

client/src/components/Navbar/index.js
client/src/components/NewClientForm/index.js
client/src/components/NewEmpForm/index.js
client/src/components/NewTeamForm/index.js
client/src/components/Progress-Bar/index.js
client/src/components/RewardsContainer/index.js
client/src/components/StatCard/index.js
client/src/components/StatCardContainer/index.js
client/src/components/TicketTableMobile/index.js
client/src/pages/Dashboard/index.js
client/src/pages/Profile/index.js

Mobile responsive updates

---

client/src/components/SignupCard/index.js
client/src/pages/Dashboard/index.js

- Updated Signup Page to make content centered
- Updated filter logic on dashboard to exclude Completed tickets from the My Tickets filter option
- Removed console logs

Signup format and dashboard filter changes

---

client/src/App.js
client/src/components/CreateTicketModal/index.js
client/src/components/EmployeeCardContainer/index.js
client/src/components/LoginCard/index.js
client/src/components/ManageTicketModal/index.js
client/src/components/NewEmpForm/index.js
client/src/components/NewTeamForm/index.js
client/src/components/ProfileForm/index.js
client/src/components/Progress-Bar/index.js
client/src/components/RewardsContainer/index.js
client/src/components/SignupCard/index.js
client/src/components/StatCardContainer/index.js
client/src/components/TicketTable/index.js
client/src/components/TicketTableMobile/index.js
client/src/pages/Dashboard/index.js
client/src/pages/Org/index.js
client/src/pages/Profile/index.js
client/src/utils/API.js
controllers/authController.js
controllers/clientController.js
controllers/orgController.js
controllers/rewardController.js
controllers/tagController.js
controllers/ticketController.js
controllers/userController.js

- Fixed profile role caption phrase
- Cleaned up all console logs
- Cleaned up all class=

Fixed bug with profile role caption; removed console.logs not needed

---

client/src/pages/Dashboard/index.js
client/src/utils/API.js
controllers/ticketController.js
routes/api/ticket.js

created new route for AllTicketsByOrg - used to filter AllTickets to just be for a certain org

Admin seeing all Org Ticket Data bug fix

---

client/src/pages/Org/index.js
controllers/clientController.js

- Patched bug with New Client validation with basic form level validation to prevent a user from being created during the new client creation process curing an error.

Bug new client validation

---

client/src/components/CommentsContainer/index.js
client/src/components/ManageTicketModal/index.js

Updated day js format function to show date and time via conversion function. just added some code into two functions, no more than two line updates total

dayjs updates to show comment time

---

client/src/components/EmployeeCardContainer/index.js
client/src/components/RewardsContainer/index.js
client/src/pages/Profile/index.js
package-lock.json
package.json

**New dependency- run NPM I**
Updated row/col/spacing/container layout to remove some causing weird spacing but aside from that everything was original code with popver stuff added, and arrows removed. 
Demo video:
https://user-images.githubusercontent.com/72420733/119570393-0c9bd400-bd7e-11eb-9d7b-f39f1c21e7f7.mp4

Ryan popover try rewards

---

client/src/components/CreateTicketModal/index.js

Task title entry validation

---

client/src/pages/Dashboard/index.js
client/src/utils/API.js
controllers/clientController.js
routes/api/client.js

- Fixed bug that was showing all clients for all Orgs
- Added new route to pull all clients using Org ID

added a new route AllClientsByOrg to only pull clients for that org

---

client/src/components/HomePageCard/index.js
seeds/reward-seeds.js
seeds/user-client-org-1.js
seeds/user-seed-org-1-team-1.js

- Adjusted seeds
- Cleaned up homepage by removing "."

Cleaned up homepage slightly, adjusted seeds > added rewards for team 2

---

client/src/pages/Profile/index.js
client/src/pages/Profile/profile.css

- Commented out icon profile button

Commented out Profile icon button as it was not working well
